### ISSUE TITLE
how to use it ?

### ISSUE THREAD

**Issue by salleman33** [overleaf/metrics-module#49]
Hi, 

I try to use this metrics module in sharelatex/overleaf instance. I saw that metrics is integrated in the differents modules of overleaf.
For exemple, in the real-time module, I saw that the method ` Metrics.injectMetricsRoute(app)` is called. But when I try to request on port 3026 /metrics, I get an error : 
```
default@sharelatex-17-db2lv:/$ curl 127.0.0.1:3026
real-time-sharelatex is alive
default@sharelatex-17-db2lv:/$ curl 127.0.0.1:3026/metrics
not implemented in statsd
```
Am I miss something ? 

Regards,

**Comment by das7pad** [comment]
Hi there,

You seem to be using version 2 of this library. It uses the `statsd` backend by default and requires an external service that listens for metrics data.
Starting with version 3 (or when using `USE_PROM_METRICS=true` in v2) the prometheus backend is in use. This backend collects metrics internally and exposes them on the `/metrics` endpoint.
Beware that this is an otherwise undocumented area we do not support at this time.

Good luck!
Jakob
